#!/bin/bash

# remove files
echo "Removing /opt/py_finder, needs user privileges"
sudo rm -rf /opt/py_finder/

# Removing py_finder.desktop and py_finder.svg pixmap
echo "Removing py_finder.desktop and py_finder.svg pixmap, requires superuser privileges"
sudo rm /usr/share/applications/py_finder.desktop
sudo rm /usr/share/pixmaps/py_finder.svg

# Removing .data.xml
echo "Removing ~/.local/.data.xml"
USER=`whoami`
rm "/home/$USER/.local/.data.xml"
status=$?
if [ $status -eq 0 ];then
	echo -e "Application uninstalled successfully..."
fi
