#!/bin/bash

# Check for user privileges
user=$(whoami)
if [ $user != root ];
then
echo User needs root privileges
exit
else
echo Good man, you are root
fi


# Install all dependencies & python-qt4
apt-get install python-qt4



